set(MICROPY_BOARD_NAME "RP2350_PIZERO2")
set(MICROPY_MCU_NAME "RP2350")

set(PICO_NUM_GPIOS 48)

# フラッシュ / RAM サイズ
set(MICROPY_FLASH_SIZE 16384K)
set(MICROPY_RAM_SIZE 520K)

# USB 設定（仮のVID/PID）
set(MICROPY_HW_USB_VID 0x2E8A)
set(MICROPY_HW_USB_PID 0x000A)
set(MICROPY_HW_USB_PRODUCT "RP2350-PiZERO")
set(MICROPY_HW_USB_MANUFACTURER "Custom")

# 有効化する機能
set(MICROPY_PY_MACHINE_I2C 1)
set(MICROPY_PY_MACHINE_SPI 1)
set(MICROPY_PY_MACHINE_UART 1)
set(MICROPY_PY_MACHINE_PWM 1)
set(MICROPY_PY_MACHINE_ADC 1)

list(APPEND PICO_BOARD_HEADER_DIRS ${MICROPY_BOARD_DIR})
